// Generated by CoffeeScript 1.10.0
(function() {
  var DEFAULT_SERVER, fetch, toQueryString;

  fetch = require('node-fetch');

  DEFAULT_SERVER = "https://leanote.com";

  toQueryString = function(data) {
    var items;
    items = Object.keys(data).map(function(v) {
      var value;
      value = data[v];
      if (typeof value === 'string') {
        value = encodeURIComponent(value);
      }
      return v + "=" + value;
    });
    return items.join('&');
  };

  module.exports = function(token, server) {
    if (server == null) {
      server = DEFAULT_SERVER;
    }
    return {
      addNote: function(title, notebook, content) {
        return fetch(server + "/api/note/addNote?token=" + token, {
          method: 'POST',
          body: toQueryString({
            NotebookId: notebook,
            Title: title,
            IsMarkdown: true,
            Content: content
          }),
          headers: {
            "Content-Type": "application/x-www-form-urlencoded"
          }
        }).then(function(res) {
          return res.json();
        });
      },
      getNotebooks: function() {
        return fetch(server + "/api/notebook/getNotebooks?token=" + token).then(function(res) {
          return res.json();
        }).then(function(notebooks) {
          return notebooks.map(function(notebook) {
            return {
              id: notebook['NotebookId'],
              name: notebook['Title']
            };
          });
        });
      }
    };
  };

  module.exports.login = function(email, pwd, server) {
    if (server == null) {
      server = DEFAULT_SERVER;
    }
    return fetch(server + "/api/auth/login?email=" + email + "&pwd=" + pwd).then(function(res) {
      if (!res.ok) {
        throw res.statusText;
      }
      return res.json();
    }).then(function(data) {
      if (!data['Ok']) {
        throw data['Msg'];
      }
      return data.Token;
    });
  };

}).call(this);

//# sourceMappingURL=lea-api.js.map
