// Generated by CoffeeScript 1.10.0
(function() {
  var READABILITY_TOKEN, fetch, he, htmlparser;

  fetch = require('node-fetch');

  he = require('he');

  htmlparser = require("htmlparser2");

  READABILITY_TOKEN = process.env.READABILITY_TOKEN || "511719798a4df8ef1221d3ef5ce944013b59ec8e";

  module.exports.readabilityFetchContent = function(url) {
    return fetch("https://www.readability.com/api/content/v1/parser?url=" + url + "&token=" + READABILITY_TOKEN).then(function(res) {
      if (!res.ok) {
        throw res.statusText;
      }
      return res.json();
    }).then(function(data) {
      data['content'] = he.decode(data['content']);
      return data;
    });
  };

  module.exports.getLinks = function(content) {
    var images, parser;
    console.log(content);
    images = [];
    parser = new htmlparser.Parser({
      onopentag: (function(_this) {
        return function(name, attribs) {
          if (name === 'img' && attribs.src) {
            return images.push(attribs.src);
          }
        };
      })(this)
    });
    parser.write(content);
    parser.end();
    return images;
  };

}).call(this);

//# sourceMappingURL=utils.js.map
